### ISSUE TITLE
C# (programming languange) can't be selected or searched for

### ISSUE THREAD

**Issue by AnjaLeBlanc** [UoMResearchIT/RSESkillsGraph#10]
![image](https://user-images.githubusercontent.com/2316693/145541713-c308e6fe-fe43-49d6-b718-9c7d44894cd0.png)

only other C languages show

**Comment by ianhinder** [comment]
Fixed now that we use "C Sharp", which is the actual wikipedia title (with ' (programming language)' removed for display).
![image](https://github.com/UoMResearchIT/RSESkillsGraph/assets/213274/51803f0e-8197-4ce3-986f-ccc720079964)
