### ISSUE TITLE
Fix invalid interests

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/RSESkillsGraph#50]
Please could @Adina-Rahim @PhilBradbury @PBarnby @TheresaTeng @ajerrison-manchester @nigeldgreen @Scottan @cjfullerton @DrJonnyT @awaisk0 @CatherineMcGuire @emmasimp @Josh-Woodcock @louiselever take a look at their people.json entries, and fix the following to be wikipedia article titles?  I've already fixed the ones I could do, but I wasn't sure what to do about the remaining ones.

If it's not possible, as you really want to list something for which wikipedia doesn't have a specific article, we can create an additional "allowed" list.

```
Invalid titles:
  Alexa Skill Development (Adina Rahim)
  Analysis of Large Graphs: Trust Rank and Webspam (Adina Rahim)
  Application design (Phil Bradbury, Patricia Barnby, Theresa Teng, Andrew Jerrison, Nigel Green)
  Association Rule Mining (Adina Rahim)
  Chemistry-Climate modelling (Scott Archer-Nicholls)
  Correctness testing (Ian Hinder)
  Deep Learning for Computer Vision (Adina Rahim)
  FCM make (Scott Archer-Nicholls)
  GitHub Actions (Chris Fullerton)
  Natural environmental (Jonny Taylor)
  React Testing Library (Awais Khan)
  Streamlit (Catherine McGuire, Emma Simpson)
  VRTK (Josh Woodcock, Louise Lever)
  vis.js (Andrew Jerrison)
```

Note that the tests are failing until these are fixed, so don't assume if you make a change that the failing test is caused by you!

**Comment by DrJonnyT** [comment]
I've made a new PR branch for my edit, but it doesn't seem to have run any actions- was it supposed to?

**Comment by ianhinder** [comment]
Haha!  It also doesn't show the check immediately; you have to refresh the page after creating the PR to even see that it is waiting to run the check!

**Comment by rowleya** [comment]
After some recent PRs, the list is now:

-   Alexa Skill Development (@Adina-Rahim)
-   Analysis of Large Graphs: Trust Rank and Webspam (@Adina-Rahim)
-   Application design (@PBarnby)
-   Association Rule Mining (@Adina-Rahim)
-   Chemistry-Climate modelling (@Scottan)
-   Deep Learning for Computer Vision (@Adina-Rahim)
-   FCM make (@Scottan)
-   GitHub Actions (@cjfullerton)
-   Software Carpentry (@Josh-Woodcock)
-   Streamlit (@CatherineMcGuire)
-   VRTK (@Josh-Woodcock)


An option for a fix would be to add an exception list for when Wikipedia doesn't cover the topic in question.  I would then suggest the following changes (where ```exception``` means it should go in the exception list):

 - Alexa Skill Development (@Adina-Rahim)  🠂 _Amazon Alexa_ **or** _Alexa Skills_ ```exception```
 - Analysis of Large Graphs: Trust Rank and Webspam (@Adina-Rahim) 🠂 _TrustRank_ **and** _WebSpam_ ```exception```
 - Application design (@PBarnby) 🠂 _Software Desgin_ **or** _User Interface Design_ **or** _Mobile app development_
 - Association Rule Mining (@Adina-Rahim) 🠂 _Association Rule Learning_
 - Chemistry-Climate modelling (@Scottan) 🠂 _Climate Model_
 - Deep Learning for Computer Vision (@Adina-Rahim) 🠂 _Convolutional neural network_ **and/or** _Computer vision_
 - FCM make (@Scottan) 🠂 _Fortran_ **or** _FCM Make (software) _ ```exception```
 - GitHub Actions (@cjfullerton) 🠂 _GitHub Actions_ ```exception```
 - Software Carpentry (@Josh-Woodcock) 🠂 _The Carpentries_
 - Streamlit (@CatherineMcGuire) 🠂 _Streamlit (software) _ ```exception```
 - VRTK (@Josh-Woodcock) 🠂 _Virtual Reality Toolkit (software)_ ```exception```

This firstly would require an exception list, but if anyone tagged wants to make changes to the above, please do suggest alternatives, or make PRs if you can find Wikipedia suggestions that match better.

**Comment by ianhinder** [comment]
@rowleya The above proposal looks good to me.  Now that we have the ability to add exceptions, would you have some time to make a PR for the above?  We could ask for a final check on the PR from the tagged people above before we merge it.

**Comment by rowleya** [comment]
PR Done - note it still fails on canonicalisation.
