### ISSUE TITLE
Add link to the deployed skills graph

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/RSESkillsGraph#63]
https://rseskillsgraph.itservices.manchester.ac.uk/

**Comment by ianhinder** [comment]
The reason that this was done is that this code was hosted in multiple places; one in the [Research Software Reactor](https://github.com/research-software-reactor/rse-skills-graph) and at University of Manchester, so there was no one single link that would have been correct. I guess both could have been added.

The RSR version is not maintained, and I don't think we want to worry about it anymore. So it's probably fine to have this link here.

This also relates to #71, in that the code repository should represent a generic reusable component, independent of where it is deployed or how it is configured.

But until that's the case, it's fine to add the link if you think it would be useful.

**Comment by gcapes** [comment]
Thanks. I was actually thinking it could go in the "About" section of the repo like I've got here - at least that's where I was looking for the link:
![image](https://github.com/user-attachments/assets/8fb7d8e2-fe58-4f92-90e6-e70ff86ac89e)

**Comment by ianhinder** [comment]
Done.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/916e1ebc-4cb2-4e0e-a199-71b2e8ca42e8">
